name: filmix_watch
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  http: ^0.12.1
  html: ^0.14.0+3
  hive: ^1.4.1+1
  path_provider: ^1.6.10
  fluttertoast: ^4.0.1
  rxdart: ^0.24.1
  connectivity: ^0.4.8+2
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.2.0
  url_launcher: ^5.4.10
  cupertino_icons: ^0.1.3
  filesize: ^1.0.4
  video_player: ^0.10.11+1
  flutter_downloader: ^1.4.4
  filesystem_picker: ^1.0.0
  permission_handler: ^5.0.1+1
  open_file: ^3.0.1
  

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
